from turtle import *
tela = Screen()
cao = Turtle()
cao.color("red")
cao.forward(70)
cao.right(90)
cao.forward(200)
gato = Turtle()
gato.color("blue")
gato.right(90)
gato.forward(200)
gato.left(90)
gato.forward(70)
lebre = Turtle()
lebre.color("green")
lebre.forward(120)
lebre.right(90)
lebre.forward(200)
lebre.right(90)
lebre.forward(50)
pangolim = Turtle()
pangolim.color("yellow")
pangolim.right(90)
pangolim.forward(240)
pangolim.left(90)
pangolim.forward(70)
pangolim.left(90)
pangolim.forward(40)
